### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount" : 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount" : 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "c0f54434615543f8a9cb33a2b803259a",
  "accountNumber": "1000000002",
  "amount" : 100
}

### query transaction
GET http://localhost:8080/transaction/346057c037364e0db2f5b89dc1e8ce36